### ISSUE TITLE
Issue when training agent

### ISSUE THREAD

**Issue by Adrien2112** [dgriff777/a3c_continuous#1]
Hello !

Thanks for the code.

I have an issue when running the command "python main.py --workers 6 --env BipedalWalker-v2 --save-max True --model MLP --stack-frames 1" :

Ghostyn@DESKTOP-BBU0957:~/a3c_continuous$ python main.py --workers 6 --env BipedalWalker-v2 --save-max True --model MLP --stack-frames 1
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from gym.configuration import undo_logger_setup
ModuleNotFoundError: No module named 'gym.configuration'

Can you help ?

Adrien

**Comment by dgriff777** [comment]
Hi! Yeah this is due to the update to gym. I had code above to get rid of annoying gym logger but will cause error in updated gym. Just comment out in the main.py script like so:
```
#from gym.configuration import undo_logger_setup
import time

#undo_logger_setup()
```

Will work fine after that

**Comment by Adrien2112** [comment]
Thank you the problem is resolved !
