### ISSUE TITLE
How to save the best policy

### ISSUE THREAD

**Issue by huguyuehuhu** [dgriff777/a3c_continuous#2]
Hi, @dgriff777 , I new to RF learning. I saved a 'best model' through your code(`main.py` in `A3C_continous`), but when use the "best policy"  to evaluate , it's reward fluctuating violently. 
![](https://user-images.githubusercontent.com/25881545/37567462-5377ae42-2b02-11e8-97ca-0ce4d943c16f.png)
I guess the saved policy actually is not the truly "best policy" but only the best in a special episode during training) , Is there any alternative way to save a stable and truly "best policy".
Thank you in advance!

**Comment by dgriff777** [comment]
Hi @huguyuehuhu, the saved model will perform with about the same consistency that you see it scoring in training at time model is saved. The environment is changing every episode so it takes a while to a policy is made that is consistent on almost all Hardcore Bipedal episodes

**Comment by huguyuehuhu** [comment]
@dgriff777 sorry, I don't understand you well.The training reward is not stable 
![figure_1](https://user-images.githubusercontent.com/25881545/37721172-cc37d024-2d63-11e8-8bb6-b93bbf29f954.png)
, so when you save the "max reward policy" near 100 episode(orange dot in figure), is actually saved a best policy **special** to episode near 100, right? when I write  a evaluate code, similar like your [discrete version,](https://github.com/dgriff777/rl_a3c_pytorch/blob/master/gym_eval.py) I find the result 
![image](https://user-images.githubusercontent.com/25881545/37721424-5fe19774-2d64-11e8-907b-3deb9908c8bc.png). So , that why I say it not stable, it's reward fluctuating violently;

**Comment by dgriff777** [comment]
@huguyuehuhu Watch the agent run ten episodes (render the environment) and you will see why its fluctuating. The environment is very different every episode. This is one of the hardest if not the hardest environment in the openai gym collection of environments for training RL agents. It took 1-2 days on a 72cpu core machine running 64 worker threads to get a consistent sufficient reward model.

I think once you watch agent with ```--render True``` I think should explain answer for you best though

**Comment by huguyuehuhu** [comment]
@dgriff777 I got it , thank you very much! May be I should wait until  the 'mean reward '  not the 'episode reward ' is convergent.
