### ISSUE TITLE
learn from 2D pixel array / conv2D

### ISSUE THREAD

**Issue by dusty-nv** [dgriff777/a3c_continuous#3]
Hi @dgriff777 , thanks for your repo.  Was wondering if you might be able/interested to add a 2D convolution model (i.e. using `Conv2D` as opposed to `Conv1D` like is in [`A3C_CONV`](https://github.com/dgriff777/a3c_continuous/blob/50bda10bd185772f626eb46a2955368c43b01ca9/model.py#L13) today) to learn from pixel array as opposed to learn from 1D parameters?  Thanks!

**Comment by dgriff777** [comment]
Hi @dusty-nv, so attached my other repo below with Conv2D example. Hope that helps :)

https://github.com/dgriff777/rl_a3c_pytorch

**Comment by dusty-nv** [comment]
Thank you!  I will look into it.


-------- Original message --------
